submodule:
	briantakita.me:
		./app:
			∋ @rappstack/domain--server/logo
			.onError: remove error noise: only print error.message, error.stack
	domain--server:
		+ ./logo:
			+ logo_image_
			+ logo_image__set
			+ logo_image_T
			+ logo_image__enable_
			+ logo_image__height_
			+ logo_image__src_
			+ logo_image__width_
	domain--server--blog:
		./ctx: ∋ @rappstack/domain--server/logo
		- ./logo: move to @rappstack/domain--server/logo:
			- logo_image_T
			- logo_image
			- logo_image__enable
			- logo_image__height
			- logo_image__src
			- logo_image__width
		./site: fix: value:
			site__page__post_count_
			site__home__post_count_
	ui--server--blog: ./header: blog__header: ∋ @rappstack/domain--server/logo